name: Merge PRs
on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
jobs:
  automerge:
    name: Auto Merge
    uses: XNXKTech/workflows/.github/workflows/dependabot-auto-merge.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.CI_PAT }}