name: Tests

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.editorconfig'
      - '.gitignore'
      - '.mergify.yml'
      - 'LICENSE**'

jobs:
  phpunit:
    name: PHP Test
    uses: XNXKTech/workflows/.github/workflows/php-test.yml@main